### ISSUE TITLE
Unhandled Exception - Any Pointers?

### ISSUE THREAD

**Issue by Jiriteach** [zimbres/UptimeKumaRemoteProbe#4]
Thanks for the work on this. Have set it up via Docker as follows (uses Docker Compose) - 

```
name: ukrp
services:
    uptime-kuma-remote-probe:
        container_name: ukrp
        volumes:
            - type: bind
              source: '/home/administrator/Docker/ukrp/appsettings.json'
              target: /app/appsettings.json
        image: zimbres/uptime-kuma-remote-probe:latest
```

Container launches but then exits with the following error - 

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at UptimeKumaRemoteProbe.Worker.LoopAsync(Configurations configurations) in /src/Worker.cs:line 70
   at UptimeKumaRemoteProbe.Worker.ExecuteAsync(CancellationToken stoppingToken) in /src/Worker.cs:line 58
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Program.<Main>$(String[] args) in /src/Program.cs:line 27
   at Program.<Main>(String[] args)
```

I've setup my appsettings.json and also a new monitor with the settings as per your example.

<img width="349" alt="Screenshot 2023-11-28 at 19 57 31" src="https://github.com/zimbres/UptimeKumaRemoteProbe/assets/2116446/0c8e6e98-89ab-4cc7-a74a-56cba7407a9b">

**Comment by Jiriteach** [comment]
Issue was to do with the latest Docker tag. Had to pull the version and that works! Thanks
